services:
  fintrack-db:
    image: postgres:17
    container_name: fintrack-db
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
      POSTGRES_DB: fintrack_db
    ports:
      - "5433:5432"
    volumes:
      - fintrack_pgdata:/var/lib/postgresql/data

volumes:
  fintrack_pgdata:
